tittle: Daniel Okoli
<p align="center">
  <img src="/assets/img/Whatsapp_image.jpeg" alt="Daniel Okoli Logo" width="150" style="border-radius: 10px;" />
</p>
Logo: /assets/img/Whatsapp_image.jpeg
description: Data Analyst Portfolio
Show_downloads: true
theme: jekyll-theme-minimal
